---

cluster_name: rancher

nodes:

{% for item in groups[‘Scene-1’] %}
    address: {{ hostvars[item][‘ansible_default_ipv4’][‘address’] }
{% endfor %}


services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

network:
  plugin: flannel

ingress:
  provider: nginx
