cluster_name: rancher

nodes:
  - address: hostvars[inventory_hostname]['ansible_default_ipv4']['master']
    user: root                       # username. you must have ssh access to the Server
    role: [controlplane,worker,etcd]

  - address: hostvars[inventory_hostname]['ansible_default_ipv4']['node-1']
    user: root                       # username. you must have ssh access to the Server
    role: [worker]

  - address: hostvars[inventory_hostname]['ansible_default_ipv4']['node-2']
    user: root                       # username. you must have ssh access to the Server
    role: [worker]

  - address: hostvars[inventory_hostname]['ansible_default_ipv4']['node-3']
    user: root                       # username. you must have ssh access to the Server
    role: [worker]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

network:
  plugin: flannel

ingress:
  provider: nginx


#{{ hostvars.{{ inventory_hostname }}.ansible_ssh_host }}"