cluster_name: rancher

nodes:
  - address: 89.42.141.31
    user: root   
                    # username. you must have ssh access to the Server
    role: [controlplane,worker,etcd]

  - address: 89.42.141.254
    user: root    
                   # username. you must have ssh access to the Server
    role: [controlplane,worker,etcd]

  - address: 89.42.141.41
    user: root     
                  # username. you must have ssh access to the Server
    role: [controlplane,worker,etcd]

  - address: 89.42.141.166
    user: root             
          # username. you must have ssh access to the Server
    role: [controlplane,worker,etcd]
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

network:
  plugin: flannel

ingress:
  provider: nginx

# hostvars[inventory_hostname]['ansible_default_ipv4']['address']
#{{ hostvars.{{ inventory_hostname }}.ansible_ssh_host }}"
